[project]
name = "cosciapollo"
version = "0.1.2"
description = "A lot of chicken"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-telegram-bot>=22.5",
    "requests>=2.32.5",
]
